TrueVote.Web/Entities/ReceivedVote.cs
namespace TrueVote.Web.Entities;

public class ReceivedVote(Guid id, Guid voteOptionDetailsId)
{
    public Guid Id { get; init; } = id;
    public DateTime CreatedAt { get; init; } = DateTime.Now;
    public  VoteOptionDetails VoteOptionDetails { get; set; }
    public Guid VoteOptionDetailsId { get; set; } = voteOptionDetailsId;
}

TrueVote.Web/Entities/VoteOption.cs
namespace TrueVote.Web.Entities;

public class VoteOption(Guid id, int optionKey)
{
    public Guid Id { get; init; } = id;
    public int OptionKey { get; init; } = optionKey;
    public DateTime CreatedAt { get; init; } = DateTime.Now;
}

TrueVote.Web/Entities/VoteOptionDetails.cs
namespace TrueVote.Web.Entities;

public class VoteOptionDetails
{
    public Guid Id { get; set; }
    public int OptionKey { get; set; }
    public string FilePath { get; set; }
    public IEnumerable<ReceivedVote> ReceivedVotes { get; set; }
}

TrueVote.Web/Entities/VoteReportByOption.cs
using Microsoft.EntityFrameworkCore.Metadata;

namespace TrueVote.Web.Entities;

public sealed class VoteReportByOption
{
    public VoteOptionDetails VoteOptionDetails { get; private set; }
    public int ReceivedVotesAmount { get; private set; }
    public int ReceivedVotesPercenteage { get; private set; }

    public VoteReportByOption(VoteOptionDetails details, int receivedVOtesAmount, int votesForALlCompetitors)
    {
        VoteOptionDetails = details;
        ReceivedVotesAmount = receivedVOtesAmount;

        if (ReceivedVotesAmount > 0)
            ReceivedVotesPercenteage = (ReceivedVotesAmount * 100) / votesForALlCompetitors;
    }
}

TrueVote.Web/Models/ErrorViewModel.cs
namespace TrueVote.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

TrueVote.Web/Controllers/VotesController.cs
using Microsoft.AspNetCore.Mvc;
using TrueVote.Web.Services.Interfaces;

namespace TrueVote.Web.Controllers;

public sealed class VotesController : Controller
{
    public async Task<IActionResult> Index([FromServices] IVotationReportService votationDetailsService) 
        => View(await votationDetailsService.GetAsync());

    public async Task<IActionResult> Create([FromServices] IVoteOptionDetailsService voteOptionsDetailsRepository)
        => View(await voteOptionsDetailsRepository.GetAsync());


    /// <summary>
    /// Submits a new vote for a VoteOption
    /// </summary>
    /// <param name="voteOption">Vote option</param>
    /// <param name="submitVoteService">Service to be called by DI</param>
    [HttpPost]
    [Route("/Votes/Submit/{voteOption}")]
    public async Task<IActionResult> Submit(
        [FromRoute] int voteOption,
        [FromServices] ISubmitVoteService submitVoteService)
    {
        await submitVoteService.CreateAsync(voteOption);
        return Accepted();
    }
}

TrueVote.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - TrueVote.Web</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
</head>
<body>

@RenderBody()


@* <footer class="border-top footer text-muted"> *@
@*     <div class="container"> *@
@*         &copy; 2024 - TrueVote.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
@*     </div> *@
@* </footer> *@
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TrueVote.Web/Views/Votes/Create.cshtml
@model IEnumerable<TrueVote.Web.Entities.VoteOptionDetails>

<h1>Vota ai</h1>
<div class="grid-container">
    @foreach (var voteOptions in Model)
    {
        <div class="grid-item">
            <img src="@Url.Content($"~/{@voteOptions.FilePath}")" alt="image">
            <button class="vote-btn" onclick="submitVote(@voteOptions.OptionKey)">Vote</button>
        </div>
    }
</div>

@section scripts{
    <script type="text/javascript" src="~/lib/signalr/signalr.js"></script>
    <script type="text/javascript">
        
        var hubConnection = new signalR.HubConnectionBuilder().withUrl("/hubs/vote").build();
        hubConnection.start();

        function submitVote(voteOption){
            let url = `@Url.Action("Submit", "Votes")/${voteOption}`;

            fetch(url,{method: 'POST'})
                .then(response => {
                    if (!response.status === 201) {
                        throw new Error('Network response was not ok ' + response.statusText);
                    }
                    
                    hubConnection.send('OnVoteCreated', voteOption);
                })
                .catch(error => {
                    console.error('There has been a problem with your fetch operation:', error);
                });         
        } 
    </script>>
}

TrueVote.Web/Views/Votes/Index.cshtml
@model IEnumerable<TrueVote.Web.Entities.VoteReportByOption>

<h1>Relatório de Votações</h1>
<div class="report-container">
    @foreach (var report in Model)
    {
        <div class="report-item">
            <img src="@Url.Content($"~/{@report.VoteOptionDetails.FilePath}")" alt="image">
            <p>Votos: <span class="vote-count" id="voteoption'@report.VoteOptionDetails.OptionKey'">@report.ReceivedVotesAmount</span></p>
        </div>
    }
</div>

@section scripts{
    <script type="text/javascript" src="~/lib/signalr/signalr.js"></script>
    <script type="text/javascript">
        var hubConnection = new signalR.HubConnectionBuilder().withUrl("/hubs/vote").build();
        hubConnection.start();

        hubConnection.on('OnVoteCreated', (val) =>{
            let optionThatReceivedANewVote = document.getElementById(`voteoption'${val}'`);
            optionThatReceivedANewVote.textContent = parseInt(optionThatReceivedANewVote.textContent) + 1;
        });

    </script>
}